#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_ansible="$(ansible --version 2>/dev/null | awk 'NR==1 {print $2}' || true)"
  jq -n \
    --arg ansible "$ver_ansible" \
      '{ansible: $ansible}'
}

version "$@"
